version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-grants-desirability-scoring:
    build:
      target: development
    image: ffc-grants-desirability-scoring-development
    container_name: ffc-grants-desirability-scoring-development
    ports:
      - "3002:3000"
      - "9231:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
