version: '3.8'

services:
  ffc-grants-desirability-scoring:
    build:
      context: .
      target: production
    image: ffc-grants-desirability-scoring
    container_name: ffc-grants-desirability-scoring
    environment: {}
