version: '3.8'

x-common-migration: &common-migration
  POSTGRES_HOST: ${POSTGRES_HOST:-ffc-grants-desirability-scoring-postgres}
  SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
  SCHEMA_ROLE: ${POSTGRES_SCHEMA_ROLE:-postgres}
  SCHEMA_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
  SCHEMA_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}

x-common-postgres: &common-postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: ${POSTGRES_DB:-ffc_grants_desirability_scoring}
  POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD:-ppp}
  POSTGRES_USER: ${POSTGRES_ADMIN_USERNAME:-postgres}

services:
  database-up:
    image: liquibase/liquibase:3.10.x
    environment:
      << : *common-migration
      << : *common-postgres
    entrypoint: >
      sh -c "/scripts/migration/database-up"
    depends_on:
      - ffc-grants-desirability-scoring-postgres
    volumes:
      - ./changelog/:/liquibase/changelog/
      - ./scripts/:/scripts/

  database-down:
    image: liquibase/liquibase:3.10.x
    environment:
      << : *common-migration
      << : *common-postgres
    entrypoint: >
      sh -c "/scripts/migration/database-down"
    depends_on:
      - ffc-grants-desirability-scoring-postgres
    volumes:
      - ./changelog/:/liquibase/changelog/
      - ./scripts/:/scripts/

  ffc-grants-desirability-scoring-postgres:
    image: postgres:11.4-alpine
    environment: *common-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
