{{- include "ffc-helm-library.container-secret" (list . "ffc-grants-desirability-scoring.container-secret") -}}
{{- define "ffc-grants-desirability-scoring.container-secret" -}}
stringData:
  POSTGRES_USER: {{ .Values.postgresService.postgresUser | quote }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.appInsights.key | quote }}
{{- end -}}
