environment: development
name: ffc-grants-desirability-scoring
namespace: ffc-grants
workstream: ffc-grants
image: ffc-grants-desirability-scoring

labels: {}

appInsights:
  key: not-a-real-key

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: ffc-grants-desirability-scoring-config-map

containerSecret:
  name: ffc-grants-desirability-scoring-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0
  redeployOnChange: update this field to force a change
  runAsNonRoot: true
  runAsUser: 1000

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 120Mi
  limitCpu: 120m
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  port: 3000
  messageQueueHost: dummy
  calculateScoreQueueAddress: calculate-score
  desirabilityScoreTopicAddress: desirability-score

postgresService:
  postgresDb: ffc_grants_desirability-scoring
  postgresExternalName:
  postgresHost: ffc-grants-desirability-scoring-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
